### ISSUE TITLE
领取银瓜子相关API变更

### ISSUE THREAD

**Issue by xfl03** [SeaLoong/Bilibili-LRHH#1]
获得宝箱详情
`https://api.live.bilibili.com/lottery/v1/SilverBox/getCurrentTask`
获得验证码
`https://api.live.bilibili.com/lottery/v1/SilverBox/getCaptcha?ts={TIMESTAMP}`
领取银瓜子
`https://api.live.bilibili.com/lottery/v1/SilverBox/getAward?time_start={TIME_START}&end_time={TIME_END}&captcha={CAPTCHA}`

**Comment by SeaLoong** [comment]
Updated
2018-03-10
