### ISSUE TITLE
关于领瓜子开启失败的解决方法

### ISSUE THREAD

**Issue by yxok200** [SeaLoong/Bilibili-LRHH#10]
本人在多个终端（不同线路）挂机，都出现不能自动领取瓜子的问题
初略看了看，这个OCRAD.js居然有3M多大，初步判断应该是greasyfork.org源的问题
于是找到了git源进行替换
// @require      https://greasyfork.org/scripts/44866-ocrad/code/OCRAD.js
替换成
// @require      https://raw.githubusercontent.com/antimatter15/ocrad.js/master/ocrad.js
替换后问题得到解决

**Comment by wxfff** [comment]
你还能挂啊，，不封1天么，，我都是用了，第2天下午就被封了，0点解封，唉，已经封了2次了，怕第3次又出什么情况，就不敢用了，，有什么办法改善，，，

**Comment by like044041** [comment]
封是因为小电视抽奖吧,与领取瓜子没关系.
我也被封了3次了,每次都挂一天抽奖,第二天抽几个就被封了,解封后重复如此.

**Comment by yxok200** [comment]
我挂了3天，一点问题都没有哦
你们用的是最新版的吗？最新的1.8.4好像是1号更新的

**Comment by like044041** [comment]
就是最新的版本啊,
更新了版本才开的抽奖,第一天挂了130多辣条,然后第二天16个辣条就无法抽奖了,昨天又挂了170多辣条,今天12个辣条后又无法抽奖了.就这样...我也不知道是不是我个人问题.

**Comment by SeaLoong** [comment]
当时我是考虑到GreasyFork的外部策略才不用github源的，也不确定TamperMonkey会不会加载其它源的脚本。不过能用的话就先这样了。

**Comment by MrPlugy** [comment]
所以现在最好不挂喽？

**Comment by yxok200** [comment]
不不不，是真的没被封，以我的修仙作息，经常上去清空道具，封了我肯定是知道的

**Comment by xfl03** [comment]
1.8.4后确实暂时未被封禁

**Comment by RT216** [comment]
用小号测试了一下，1.8.4还是会被封（今天0点）

**Comment by wxfff** [comment]
可能楼主ip没被拉黑，我大小号都会封。。悲剧啊

**Comment by yxok200** [comment]
凉了凉了，今天下午发现被封了

**Comment by chrwhy** [comment]
请问下, 这个API可以获取在线观众人数吗?

**Comment by SeaLoong** [comment]
@chrwhy 
获取在线观众人数是通过与弹幕服务器通信实现的，目前已经加入弹幕服务器有关的API(版本1.3.0)

**Comment by xfl03** [comment]
已使用腾讯云来进行存储依赖js
