### ISSUE TITLE
突然提示「访问被拒绝，您的账号可能已被关小黑屋」

### ISSUE THREAD

**Issue by Koumo-OS** [SeaLoong/Bilibili-LRHH#101]
**描述bug**
用了两个月左右，一直都很正常，今天刚打开网页就突然提示「访问被拒绝，您的账号可能已被关小黑屋」，求问前辈如何解决

**截图**
![2019-12-27_124956](https://user-images.githubusercontent.com/49365204/71501869-d071f480-28a7-11ea-8700-a900a9aae068.png)

**使用环境:**
 - 浏览器: Firefox
 - 浏览器版本: Firefox 71.0
 - 脚本的版本: 2.4.9
 - 网络情况(网速): 优，100M联通宽带

**Comment by SOYORO** [comment]
新年凌晨终于进了小黑屋

**Comment by AlsumDea** [comment]
so 解封了吗

**Comment by Koumo-OS** [comment]
> 
> 
> so 解封了吗

我是大概一周左右解封的

**Comment by onsummer** [comment]
> > so 解封了吗
> 
> 我是大概一周左右解封的

我一周了 好像还没

**Comment by Smoke-N-Mirrors** [comment]
> > > so 解封了吗
> > 
> > 
> > 我是大概一周左右解封的
> 
> 我一周了 好像还没

请问现在解封了吗, 我前天进去的问客服说要两周我才能解封

**Comment by onsummer** [comment]
> > > > so 解封了吗
> > > 
> > > 
> > > 我是大概一周左右解封的
> > 
> > 
> > 我一周了 好像还没
> 
> 请问现在解封了吗, 我前天进去的问客服说要两周我才能解封

今天解封了 长达半个月 我佛了 等两个月再撸吧 估计最近风口紧

**Comment by Smoke-N-Mirrors** [comment]
关了我整整14天, 终于出来了

**Comment by onsummer** [comment]
> 关了我整整14天, 终于出来了

恭喜 我现在是人在插件开 人不在必关
