### ISSUE TITLE
绘马祈愿

### ISSUE THREAD

**Issue by Malus-Mill** [SeaLoong/Bilibili-LRHH#102]
**描述bug**
简要描述所遇到的bug
在Bilibili Evolved (Offline)和本脚本同时开启后有很大概率会让绘马和主播公告跑掉

![image](https://user-images.githubusercontent.com/53999738/72167293-d6b6b380-3405-11ea-8aab-823aa15fbdd9.png)
![image](https://user-images.githubusercontent.com/53999738/72167382-036acb00-3406-11ea-832c-34b5605f7065.png)

**重现bug**
说明您在进行了怎样的操作后出现了bug
1. 开启俩个脚本，F5
![image](https://user-images.githubusercontent.com/53999738/72167293-d6b6b380-3405-11ea-8aab-823aa15fbdd9.png)
2. 开启单一脚本和关闭脚本，F5
![image](https://user-images.githubusercontent.com/53999738/72167382-036acb00-3406-11ea-832c-34b5605f7065.png)

**预期行为**
简要描述进行以上操作后预期的脚本行为

**截图**
如果可以，请提供有关截图

**使用环境:**
 - 浏览器: Chrome
 - 浏览器版本: 版本 79.0.3945.117（正式版本） （64 位）
 - 脚本的版本: 2.4.9，Bilibili Evolved (Offline)为最新版
 - 网络情况(): 好
 - 其他浏览器插件/脚本: Bilibili Evolved (Offline)
 - bug出现时间: 刷新后暂时并不会出现，在开始执行本脚本后就会跑掉

**其他**
并没有测试开关夜间模式所带来的影响

**Comment by Mishasama** [comment]
https://link.bilibili.com/p/eden/news#/newsdetail?id=1280
![绘马祈愿下线通知](https://i0.hdslb.com/bfs/vc/b4f6d861b78fd92d61f50639ec06a041ea4bba23.png)
已经没法测试了
@SeaLoong
