### ISSUE TITLE
舰队领奖提示“请升级APP”

### ISSUE THREAD

**Issue by Mouse0w0** [SeaLoong/Bilibili-LRHH#104]
**描述bug**
舰队领奖提示“请升级APP”

**重现bug**
1. 启用自动领奖->舰队领奖

**预期行为**
舰队领奖提示“请升级APP”

**截图**
如果可以，请提供有关截图

**使用环境:**
 - 浏览器: Chrome
 - 浏览器版本: Chromium 80.0.3987.106
 - 脚本的版本: 2.4.9
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本: 无
 - bug出现时间: 每次舰队领奖

**其他**
无

**Comment by ltc-01** [comment]
![未命名1582100546](https://user-images.githubusercontent.com/61226687/74816370-fbbc1180-5335-11ea-9463-674ace624cb5.png)
帮你补张图

**Comment by Mouse0w0** [comment]
Thanks

**Comment by awsomemasteer** [comment]
![2020 02 19-16 13](https://user-images.githubusercontent.com/53611567/74817977-ca911080-5338-11ea-9c70-c8f72660538c.png)这是我目前遇到的，同时在启动后会出现其他直播间的声音，如果可以请告诉我你的联系方式，我会把具体情况的录屏发给你，谢谢，希望尽快修复bug

**Comment by HYY-zh** [comment]
@Mouse0w0 你可以加QQ群向作者反馈，QQ群在置顶的问题里有
![20200219170837](https://user-images.githubusercontent.com/61227595/74818933-80109380-533a-11ea-9d35-3fe524f3ec56.png)

**Comment by xfl03** [comment]
怎么是你.jpg

**Comment by SeaLoong** [comment]
草，怎么是你，把33都炸出来了。
这个问题应该是接口更新了，但是这几天忙着课设没空，过大概一周吧，有机会我还是争取更新一下。

**Comment by chenyang12315** [comment]
> 草，怎么是你，把33都炸出来了。
> 这个问题应该是接口更新了，但是这几天忙着课设没空，过大概一周吧，有机会我还是争取更新一下。

原来大佬还在维护，太好了233

顺路请问Q群答案是什么呀，好像改了。

**Comment by xfl03** [comment]
接口更新 @SeaLoong 
POST `https://api.live.bilibili.com/xlive/lottery-interface/v3/guard/join`
参数
```
id
roomid
type: guard
csrf_token
csrf
visit_id
```
