### ISSUE TITLE
请升级APP

### ISSUE THREAD

**Issue by Mishasama** [SeaLoong/Bilibili-LRHH#106]
**描述bug**
舰队抽奖时触发的黄色提示

**重现bug**
说明您在进行了怎样的操作后出现了bug
1. 舰队抽奖

**预期行为**
简要描述进行以上操作后预期的脚本行为

**截图**
如果可以，请提供有关截图

**使用环境:**
 - 浏览器: Chrome
 - 浏览器版本: Chrome 77.0.3865.120
 - 脚本的版本: 2.4.9
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本: -
 - bug出现时间: 1(精确到分钟)

**其他**
若您有其他想要补充的内容，请在此说明

**Comment by xfl03** [comment]
#104 #105 
不是修了吗qwq

**Comment by Fubuki521** [comment]
![批注 2020-02-22 000658](https://user-images.githubusercontent.com/55498866/75050628-4a6cd580-5507-11ea-8c8b-dc76aadb2d9b.png)

**Comment by xfl03** [comment]
2.4.10版本已修复，@Mishasama 使用的还是2.4.9，请及时更新
