### ISSUE TITLE
监听倍率手动提高-负面效果有无

### ISSUE THREAD

**Issue by dongdongkeer** [SeaLoong/Bilibili-LRHH#110]
我手动更改了监听倍率的有关代码, 使得监听倍率可以到达10, 请问这样做是否会有负面效果?(我电脑足够强大, 不会出现卡顿问题, 我担心的是小黑屋问题)

**Comment by tangpipi** [comment]
访问过于频繁会导致bilibili api拒绝连接，弹幕什么都加载不出来，只显示个视频。但是不会小黑屋，几个小时后恢复正常，我是5倍率的时候就会这样，建议别搞10倍，加速被封

**Comment by dongdongkeer** [comment]
> 访问过于频繁会导致bilibili api拒绝连接，弹幕什么都加载不出来，只显示个视频。但是不会小黑屋，几个小时后恢复正常，我是5倍率的时候就会这样，建议别搞10倍，加速被封

哦哦谢谢您的提醒, 我今天挂了一天的15倍, 明天还是改回5倍吧
