### ISSUE TITLE
能否根据泄露源码判断出小黑屋逻辑

### ISSUE THREAD

**Issue by dongdongkeer** [SeaLoong/Bilibili-LRHH#111]
b站曾经发生过一次大型源码泄露, 相关go语言源码被上传到github, 作者大大能否根据这些代码判断出小黑屋逻辑? 如果作者没有相关源码, 可以联系我, 我保留了备份(我的大小号都没进过小黑屋而且我也不在乎b站的账号, 但是确实好奇封禁逻辑, 我自己也会研究一下的, 希望能和作者一同讨论)

**Comment by xfl03** [comment]
小黑屋逻辑不在里面

**Comment by AlsumDea** [comment]
挂了个通宵，gg了，希望早点出来

**Comment by dongdongkeer** [comment]
> 挂了个通宵，gg了，希望早点出来

人不能太贪心, 出来没

**Comment by AlsumDea** [comment]
> > 挂了个通宵，gg了，希望早点出来
> 
> 人不能太贪心, 出来没

暂时不挂了，等过半个月再试试，只能一边看一边挂，最好有操作
