### ISSUE TITLE
直播区被劫持？

### ISSUE THREAD

**Issue by MaxwellXiao** [SeaLoong/Bilibili-LRHH#112]
开发者你好，首先感谢你做了这个插件免费供大家使用。魔改版在升级2.4.3.21，升级后可能会出现观看一会直播后插件显示连接不上服务器，然后整个直播区都打不开了，直播也看不了。询问B站客服后得知可能是受劫持了，我尝试从网页端发出重启路由器命令，重启后恢复正常，然而不久后又重复了。自更新6h以来共发生2次。下一步我尝试先关闭您的插件观看一段时间的直播，若24h后仍没出问题，再打开插件观看直播，看一下是不是插件的问题。附图：B站直播测试：
![image](https://user-images.githubusercontent.com/47251656/76106920-ca6c6280-6012-11ea-89a8-a6792c5f4e82.png)

**Comment by MaxwellXiao** [comment]
PC和iphone都进不去直播，由于客服是在手机端点开的，故诊断在我的iphone上做的。

**Comment by jimlee2002** [comment]
有相同情况，更新插件使用一段时间后会无法使用任何bilibili直播的相关服务，网页端console和手机均显示HTTP 412 precondition failed，似乎是被服务器禁止访问了，但重启路由器可解决

**Comment by yinghaiping** [comment]
风控了，当前IP已经被限制了，重启光猫换IP就会好

**Comment by MaxwellXiao** [comment]
> 风控了，当前IP已经被限制了，重启光猫换IP就会好

新版已经修复了，更新后没有再风控过
