### ISSUE TITLE
最新脚本使用一段时间后无法访问任何直播服务

### ISSUE THREAD

**Issue by jimlee2002** [SeaLoong/Bilibili-LRHH#113]
更新脚本后使用一段时间，会出现无法使用任何bilibili直播服务的情况

 WEB端：
- 使用一段时间后直播间画面黑屏，脚本停止运作，直播间任何功能无法使用
- 悬停在顶栏个人头像处后个人头像变成默认头像，昵称消失
- 无法打开“我的直播间” ，无法访问个人“直播中心”
- 可以打开bilibili直播主页，但无法打开任何直播间
- F12打开控制台，有大量红色连接错误，报 HTTP 412，也有提示blocked的 ，似乎是被服务器禁止访问直播服务了？
- bilibili主站其他服务一切正常
 
出现问题后Android客户端情况
- 可以打开直播区的页面，但无法打开
- 同时无法打开任何直播间，提示HTTP 412 precondition failed
- 其他服务一切正常

使用环境:
 - 浏览器: Edge
 - 浏览器版本: Edge 80.0.361.66
 - 脚本的版本: 2.4.10
 - 网络情况(网速): 好
 - bug出现时间: 使用新版本脚本一段时间后

以上问题在重启路由器+关闭脚本后可以解决
如有情况复现我会上传截图

**Comment by jimlee2002** [comment]
另：无任何小黑屋的提示

**Comment by jimlee2002** [comment]
补充：魔改版在更新后（2.4.3.21）也出现了相同的问题

**Comment by MaxwellXiao** [comment]
一样的，估计是哪里改出bug了，我处理方式一样，昨晚还出问题，今上午就没事了。上一个issue就是我提的。

**Comment by MaxwellXiao** [comment]
魔改版更新25了，你更新一下试试，我现在在测试看还有没问题。

**Comment by jimlee2002** [comment]
魔改版更新后使用了5h暂无问题，应该解决了
