### ISSUE TITLE
新版现在如何

### ISSUE THREAD

**Issue by wxfff** [SeaLoong/Bilibili-LRHH#12]
2号直播间估计沦陷了
请尽量避免在那里挂机，
最好找个签约up的，

新版现在如何，我号已封2次，怕第3次永久。。。

**Comment by SeaLoong** [comment]
表示大号被封了，第二天也没解，导致没法测试新版本。挂了个小号测试。

**Comment by like044041** [comment]
..要签约UP又最好是长期无人直播间,这个要求有点难啊..有没有老哥指路?

**Comment by wxfff** [comment]
你的账号已被封禁


现在居然凌晨就封了。。。

**Comment by wxfff** [comment]
已经过去一天一夜，真的是永久封。。。

**Comment by wxfff** [comment]
中午12点，解封，，，可怕，，不敢尝试了。。。。

**Comment by like044041** [comment]
感觉挂在短号房间抽奖没用了,这两天试了一下,在短号房间点抽奖公告,地址也会有visit_id=,不知道是不是因为这个才被封号.

**Comment by wxfff** [comment]
可能跟短号没关系，主要是接口使用太频繁了，自建网页上传抽奖房号，隔离bli，抽奖不要全天运行，设定在高峰期抽，比如晚上-凌晨。。。。
