### ISSUE TITLE
求教换源问题/（如何换源）

### ISSUE THREAD

**Issue by cos-fish** [SeaLoong/Bilibili-LRHH#121]
**描述bug**
简要描述所遇到的bug
OCRAD初始化失败
**重现bug**
说明您在进行了怎样的操作后出现了bug
1. 个别直播间可以正常运行
2.大部分直播间初始化失败 

**预期行为**
简要描述进行以上操作后预期的脚本行为
希望教小白如何换源（比如我）
**截图**
如果可以，请提供有关截图

**使用环境:**
 - 浏览器: Chrome
 - 浏览器版本: 80.0.3987.116
 - 脚本的版本: 2.4.10
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本：无
 - bug出现时间: 

**其他**
若您有其他想要补充的内容，请在此说明

**Comment by Mishasama** [comment]
不看readme的close了吧😓
