### ISSUE TITLE
初始化失败

### ISSUE THREAD

**Issue by wulifuji** [SeaLoong/Bilibili-LRHH#125]
控制台报错信息：

`[自动领取瓜子]OCRAD初始化失败，请检查网络`
`ReferenceError: OCRAD is not defined`

从greasyfork安的2.4.10，但在这里似乎更到了是2.4.11？
大概……也许是该在greasyfork更新了

**Comment by wyiwyi** [comment]
我的也是

**Comment by HestiaQAQ** [comment]
我也初始化失败了

**Comment by SachiaLanlus** [comment]
把OCRAD的source換掉就好了，被爆破了
給個暫時的workaround
把第13行的
// @require      https://greasyfork.org/scripts/44866-ocrad/code/OCRAD.js
換成
// @require      https://raw.githubusercontent.com/antimatter15/ocrad.js/master/ocrad.js

**Comment by Yuii-guoguo** [comment]
https://download.guoguokm.com/js/ocrad/ocrad.js
私人地址，楼上那位的国内有墙访问不了.

**Comment by frankjoe7** [comment]
> 控制台报错信息：
> 
> `[自动领取瓜子]OCRAD初始化失败，请检查网络`
> `ReferenceError: OCRAD is not defined`
> 
> 从greasyfork安的2.4.10，但在这里似乎更到了是2.4.11？
> 大概……也许是该在greasyfork更新了

greasyforky不知道因为啥删除了，我也是2.4.10。现在就一直ocard初始化失败。
