### ISSUE TITLE
领瓜子失效

### ISSUE THREAD

**Issue by Philogag** [SeaLoong/Bilibili-LRHH#126]
**描述bug**
![Snipaste_2020-05-11_19-47-03](https://user-images.githubusercontent.com/44018455/81558649-9f124500-93c0-11ea-993c-feb47fa009b7.png)

**使用环境:**
 - 浏览器: Edge Dev
 - 浏览器版本:  84.0.502.0 (官方内部版本) dev (64 位) Chrome/84.0.4130.0
 - 脚本的版本: 2.4.10
 - 网络情况(网速): 好/一般/坏
 - 其他浏览器插件/脚本:  Bilibili Evolved (Preview)

**其他**
若您有其他想要补充的内容，请在此说明

**Comment by SachiaLanlus** [comment]
#125

**Comment by Yuii-guoguo** [comment]
> **描述bug**
> ![Snipaste_2020-05-11_19-47-03](https://user-images.githubusercontent.com/44018455/81558649-9f124500-93c0-11ea-993c-feb47fa009b7.png)
> 
> **使用环境:**
> 
> * 浏览器: Edge Dev
> * 浏览器版本:  84.0.502.0 (官方内部版本) dev (64 位) Chrome/84.0.4130.0
> * 脚本的版本: 2.4.10
> * 网络情况(网速): 好/一般/坏
> * 其他浏览器插件/脚本:  Bilibili Evolved (Preview)
> 
> **其他**
> 若您有其他想要补充的内容，请在此说明

ocrad.js的地址挂了，我换上了自己的地址就可以用了.

**Comment by luo578904042** [comment]
![image](https://user-images.githubusercontent.com/13390438/82045579-e90d6a80-96e1-11ea-988a-958a5bae7549.png)
换成gitee源可用

**Comment by MMMao0** [comment]
> ![image](https://user-images.githubusercontent.com/13390438/82045579-e90d6a80-96e1-11ea-988a-958a5bae7549.png)
> 换成gitee源可用

感谢 有用

**Comment by inpowerchiu** [comment]
> ![image](https://user-images.githubusercontent.com/13390438/82045579-e90d6a80-96e1-11ea-988a-958a5bae7549.png)
> 换成gitee源可用

感谢分享。
