### ISSUE TITLE
B站对抢辣条的行为发公告了

### ISSUE THREAD

**Issue by PeanutMelonSeedBigAlmond** [SeaLoong/Bilibili-LRHH#127]
- 链接：http://link.bilibili.com/p/eden/news#/newsDetail?id=1229

![TIM截图20200515232341](https://user-images.githubusercontent.com/25266280/82067366-377f3100-9703-11ea-8c5a-b1b3ff5a30c2.png)

**Comment by pongfcnkl** [comment]
关掉自动抽奖是不是就没问题了？

**Comment by PeanutMelonSeedBigAlmond** [comment]
> 关掉自动抽奖是不是就没问题了？

不清楚B站是如何区别脚本和真人的
