### ISSUE TITLE
规避封号失败了

### ISSUE THREAD

**Issue by Qiufeng125** [SeaLoong/Bilibili-LRHH#13]
今天被封号了。。。。。。作者继续努力。

**Comment by yinghaiping** [comment]
我也被封号了，不知道啥时候可以解封，作者大大加油啊~

**Comment by Qiufeng125** [comment]
一般的话一天就会解封，应该不会超过三天，要是还不解封就去找客服吧

**Comment by MrPlugy** [comment]
封了我三天。。。差点以为永久封禁。。。

**Comment by LoongChenxi** [comment]
现在抽奖只有辣条了、

**Comment by Naraku00** [comment]
今天被封号了  蓝瘦  留个名QAQ

**Comment by yxok200** [comment]
封个一天半天的还好接受，现在一封就是3天。。。。

**Comment by SeaLoong** [comment]
小号被封号了，目前先别用抽奖了。
我现在有个新思路(笨办法)，就是检测到抽奖后，在当前页面下创建个iframe(每有一个能抽奖的直播间就创建个)，挂在抽奖的直播间。iframe里面加载子脚本，这个子脚本只负责那个直播间的抽奖，抽奖结束后，子脚本通知父脚本删除对应的iframe。
这样不确定能不能防止封号，而且也不需要短号直播间代理抽奖了，但是估计占用的系统资源会增加不少。
还有就是没时间(高考)，有人会的话可以实现一下(可以参考我怎样实现的代理抽奖)，然后发PR。

**Comment by xfl03** [comment]
这么多天终于（？）翻车了 嘤嘤嘤

**Comment by RT216** [comment]
小号被封都快5天了。。。

**Comment by RT216** [comment]
刚刚解封。。

**Comment by lemako** [comment]
喷了 大佬还要高考

**Comment by yxtj** [comment]
@SeaLoong 我写的脚本就是类似的机制，我降低了参与概率，目前用了两天，还没被封。

**Comment by a0010028** [comment]
@yxtj 老哥你现在写的脚本情况如何，比较顺利的话能否共享一下？

**Comment by yxtj** [comment]
@a0010028 抱歉啊朋友，为了安全，我的脚本是自用的，希望你能够理解。
不过我可以提供一个非常有效而且容易实现的思路，你可以用`window.open`打开一个新窗口，再模拟点击然后用`window.close`关闭它。你需要修改这个脚本里的2个地方，一个是更改发现新抽奖之后怎么做，另一个是添加检测新页面正在进行的抽奖发现后领取关页面。如果你能够在这套脚本里定位到第一个地方，相信其他的对你都不是难事。希望对你有帮助。

**Comment by a0010028** [comment]
@yxtj 是我考虑不周...无意冒犯了，毕竟我还是知道信息安全的重要性
虽然我对代码只是懂一点毛皮，但大大提供的思路我会尝试一下的~

**Comment by yxtj** [comment]
@a0010028 没有没有。是我通过猜测和分析b站直播间的工作流程，用了一些明显的技巧，为了防止b站反制，或者延缓他们反制的进度，我不想把它拿出来。不过这个思路应该没有问题。

**Comment by lolicon0930** [comment]
@yxtj 我建议你把思路删了...破站要是搞个弹窗检测就烦了...
我从出小黑屋之后也降低了参与概率...
之前24hr全部参与是真的有点作死了...

**Comment by yxtj** [comment]
@lolicon0930 谢大佬提醒
