### ISSUE TITLE
封号回馈

### ISSUE THREAD

**Issue by ChromeHu** [SeaLoong/Bilibili-LRHH#15]
一开始被封了，以为是自动领宝箱的问题。
昨天解封，把领宝箱关了，但是有自动参与抽奖，并且有几次提示刷屏。

今天就都访问被拒。我觉得可能是自动参与抽奖太频繁，可以设置个参与抽奖的延迟吗。

**Comment by wxfff** [comment]
我第3次被封3天，前2次都是被封的次日0点解封，后来系统改版就3天
至此不敢再尝试，

白嫖党末路。。。

**Comment by ChromeHu** [comment]
那就难受了，宝箱不愿意领，看直播起劲那会记得宝箱。
抽奖的话，我一个一个点不太现实。
如果有延迟操作的话不知道会不会好，最好是随机的延迟。抽奖是随机的房间（话说抽奖不能直接用抽奖的房间号吗）能模拟像人的操作多好，抽奖以前以前有个后台打开页面，我觉得还行，占一点资源也没事。

当然都是想法，只是一个希望，一个愿望。
~~_假如我会写这东西可能自己会试一试吧。_~~

**Comment by LEORChn** [comment]
@wxfff 
那叫 穷“徒”末路
