### ISSUE TITLE
请问现在不能抢礼物了吗

### ISSUE THREAD

**Issue by czKevin1996** [SeaLoong/Bilibili-LRHH#17]
RT，在centos服务器上用firefox好像无法抢礼物？

**Comment by g2384** [comment]
因为`window.__statisObserver.__visit_id` 是undifiend？

**Comment by czKevin1996** [comment]
我没注意代码，在Chrome上好像也不行

**Comment by yxtj** [comment]
我今天也发现这个问题了，通过脚本访问`window.__statisObserver`是undifined，而直接在命令行里却是正常的。另外`window.BilibiliLive`也是undifined。
我是Ubuntu 16.04+Chrome 67.0.3396.87 (前两天刚刚升级的版本）。
我试了页面每隔一分钟测试一下，发现一直不行。现在不知道为什么。
脚本里的`window`像是一个纯净的默认对象，没有任何第三方的东西。

**Comment by SeaLoong** [comment]
该问题已解决，大概是js脚本加载顺序的问题
