### ISSUE TITLE
bili更新了开总督全站进该房间领取当前勋章20亲密

### ISSUE THREAD

**Issue by wxfff** [SeaLoong/Bilibili-LRHH#2]
希望更新一下代码

能领取亲密

大航海改版通知 http://link.bilibili.com/p/eden/news#/newsdetail?id=479
二、总督抽奖特权

用户购买总督时会立即触发全频道公告及当前房间领奖，24小时内，每一个进入该房间的用户都会增加当前佩戴勋章20点亲密度。

领取界面跟高能活动抽奖的一样，但是连接不显示在公屏聊天区，只是普通开通总督的全站横幅

界面代码

去掉替换符号

界面代码

<替换符号div data-v-01d3e770="" data-v-e1d374c0="" data-v-6f04db9e="" class="lottery-box guard-lottery guard-lottery lottery order-0">替换符号<替换符号div data-v-01d3e770="" class="title">替换符号总督上任普天同庆， 还剩余1个<替换符号/div>替换符号<替换符号!---->替换符号<替换符号div data-v-01d3e770="" class="main">替换符号<替换符号div data-v-01d3e770="" class="next-loading" style="display: none;">替换符号<替换符号/div>替换符号<替换符号/div>替换符号<替换符号div data-v-01d3e770="" class="thx">替换符号特别鸣谢<替换符号span data-v-01d3e770="" class="thx-name">替换符号blink_antimega<替换符号/span>替换符号的赠送<替换符号/div>替换符号<替换符号div data-v-01d3e770="" class="close icon-font icon-close">替换符号<替换符号/div>替换符号<替换符号/div>替换符号

**Comment by SeaLoong** [comment]
以后最好一并提供检测方式和相关接口。这个功能我目前还没有相关数据，没法更新。

**Comment by wxfff** [comment]
查看每日开总督的直播间获取20亲密度的方法
http://live.bilibili.com/p/eden/rank#/childnav/vitality/0

查看元气主播每日榜前10

我没那技术找接口啊，你晚上23点抓前10的房间看看，b站总督很少的

**Comment by ZokeeChen** [comment]
3号直播间 输入 总督 能够查询最近能够领取的房间号
![4f33d22aec5a71ae1fff3019c1ef0c61](https://user-images.githubusercontent.com/35579496/38341862-699dc210-3840-11e8-9604-a773c037f3fa.jpg)

**Comment by wxfff** [comment]
@qingfeng66

直接复制这个连接里的代码，别说不会用
https://github.com/SeaLoong/Bilibili-LRHH/blob/master/Bilibili%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.js

**Comment by qingfeng66** [comment]
我新人 不太会Orz
