### ISSUE TITLE
关于自动抽奖的问题

### ISSUE THREAD

**Issue by examrl** [SeaLoong/Bilibili-LRHH#22]
我是直接复制的github上的，为何会出现（自动抽奖）运行时出现异常，已停止。我对于脚本基本是小白= =所以来问问题了。。
直接从greasyfork上安装也是这个提示。。。麻烦了

**Comment by SeaLoong** [comment]
能重现吗，打开开发人员工具(F12)，把这一行以及下一行的错误信息截图一下。

**Comment by examrl** [comment]
![image](https://user-images.githubusercontent.com/42043868/43605499-12880dc0-96cb-11e8-8c05-b6463574684f.png)
原来直接复制就可以发图= =

**Comment by SeaLoong** [comment]
原因已经查明：ADBlock等插件阻止了脚本正常运行
