### ISSUE TITLE
新活动小金人抽奖

### ISSUE THREAD

**Issue by MrPlugy** [SeaLoong/Bilibili-LRHH#26]
小金人是分区广播，可以实现么

**Comment by SeaLoong** [comment]
目前就只监听当前房间所在分区的广播(就和直播间聊天显示的抽奖是一样的)，也不打算做监听全区广播

**Comment by MrPlugy** [comment]
3号直播间有机器人监听所有分区的广播，能否直接借助此来实现？

**Comment by SeaLoong** [comment]
理论上之后出的各种新抽奖大多都能支持，不需要更新代码。我这里的意思是不做全区广播的监听，但对于分区广播的抽奖还是可以支持的。
