### ISSUE TITLE
我的自动抽奖不能运行，请问是什么问题？

### ISSUE THREAD

**Issue by MatthewYea** [SeaLoong/Bilibili-LRHH#27]
userscript.html?id=c4b508a7-d71f-491d-bd3e-69924b2dcce1:62668 [BLRHH][18:58:1][自动抽奖]运行时出现异常，已停止
window.toast @ userscript.html?id=c4b508a7-d71f-491d-bd3e-69924b2dcce1:62668
userscript.html?id=c4b508a7-d71f-491d-bd3e-69924b2dcce1:64292 [BLRHH] TypeError: Lottery.ws.bind is not a function
    at Object.run (userscript.html?id=c4b508a7-d71f-491d-bd3e-69924b2dcce1:64156)
    at Run (userscript.html?id=c4b508a7-d71f-491d-bd3e-69924b2dcce1:64436)
    at l (userscript.html?id=c4b508a7-d71f-491d-bd3e-69924b2dcce1:5)
    at c (userscript.html?id=c4b508a7-d71f-491d-bd3e-69924b2dcce1:5)
run @ userscript.html?id=c4b508a7-d71f-491d-bd3e-69924b2dcce1:64292
userscript.html?id=c4b508a7-d71f-491d-bd3e-69924b2dcce1:62662 [BLRHH][18:58:3][自动送礼]今日亲密度未满，送礼开始
userscript.html?id=c4b508a7-d71f-491d-bd3e-69924b2dcce1:62662 [BLRHH][18:58:3][自动送礼]送礼结束，1小时后再次送礼
userscript.html?id=c4b508a7-d71f-491d-bd3e-69924b2dcce1:982 Uncaught TypeError: this.sendLoginPacket is not a function
    at WebSocket.DanmuWebSocket.addEventListener (userscript.html?id=c4b508a7-d71f-491d-bd3e-69924b2dcce1:982)
decorator.min.js?21c37247dd29f00:467 [flv.js] > Playback seems stuck at 0, seek to 0.009
value @ decorator.min.js?21c37247dd29f00:467
value @ decorator.min.js?21c37247dd29f00:467
value @ decorator.min.js?21c37247dd29f00:467

**Comment by xfl03** [comment]
请教一下您的浏览器版本

**Comment by MatthewYea** [comment]
最新的chrome

**Comment by sit17** [comment]
我log一下发现API.DanmuWebSocket的接口变了,去掉了bind接口,换成了onopen,onmessage之类的

**Comment by sit17** [comment]
我这边log看了下Lottery.ws,里面真的没bind方法,类也是websocket,  js不太熟估计跟new有问题??反正我的解决方法是把所有DanmuWebsocket的函数原型都挂到Lottery.ws上面了
Lottery.ws = new API.DanmuWebSocket(Info.uid, window[NAME].roomid);
Lottery.ws.bind = API.DanmuWebSocket.prototype.bind;
Lottery.ws.sendLoginPacket = API.DanmuWebSocket.prototype.sendLoginPacket;
Lottery.ws.sendData = API.DanmuWebSocket.prototype.sendData;
Lottery.ws.sendHeartBeatPacket = API.DanmuWebSocket.prototype.sendHeartBeatPacket;

**Comment by SeaLoong** [comment]
@sit17 惊了，你不用睡觉的吗。这个问题我估计是被浏览器的什么设置或者插件限制了，之前有人反馈过，发现是广告拦截插件的问题。但是也有人反馈关了广告拦截也没用，现在是没有头绪。

**Comment by sit17** [comment]
@SeaLoong emmm,隔一段时间存够钱就当自由程序员,可以随便做想做的,接接外包...这个问题我解决了挂一天正常的~
