### ISSUE TITLE
总督抽奖好像不能自动进行

### ISSUE THREAD

**Issue by MrPlugy** [SeaLoong/Bilibili-LRHH#29]
另外就是现在舰长和提督上舰也有亲密度的奖励了

**Comment by 526240218** [comment]
期待更新

**Comment by SeaLoong** [comment]
emmm我觉得你的期待要落空了，这段时间刚开学，等学习进程步入正轨且不出什么意外的话，我会尝试更新（况且这段时间不是白嫖的挺爽的吗，封号情况我也没怎么见过了（反正我勋章17级了XD

**Comment by 526240218** [comment]
好吧，确实不封号了。不过还是继续期待更新，白嫖到20再说。狗

**Comment by MrPlugy** [comment]
emm,所以总督抽奖失败是个例么

**Comment by SeaLoong** [comment]
emmm有当时的情况说明吗，这个应该是个例了吧。我还没遇见过

**Comment by MrPlugy** [comment]
我不太知道;-;
重新导入后打开总督抽奖也不行
