### ISSUE TITLE
目前无法使用啊？

### ISSUE THREAD

**Issue by Saver233** [SeaLoong/Bilibili-LRHH#32]
自动签到，抽奖，你所叙述的功能我这无法使用。都用过你的方法解决但是还是无效，望更新，求解谢谢。

**Comment by MrPlugy** [comment]
你看是不是设置被重置了？

**Comment by Saver233** [comment]
> 你看是不是设置被重置了？

没有啊，直播页面有挂机助手的窗口，设置领瓜子还是不行。
是不是我出问题了？
