### ISSUE TITLE
脚本对银瓜子宝箱不能正常领取?

### ISSUE THREAD

**Issue by shinji-ikari** [SeaLoong/Bilibili-LRHH#33]
这两天才注意到.脚本是挂在某个房间固定不动的.期间开其他的房间看直播.(反正脚本是提示已经有脚本在运行.)
然后就发现左下角的宝箱竟然在倒计时了. 回头看了一眼挂机的房间.显示的是"今天已领完"....等直播房间的宝箱倒计时结束之后.输入验证码.还真的领取到80银瓜子._(:з」∠)_

**Comment by SeaLoong** [comment]
设计上是当今天的每日的任务（包括领瓜子）完成后，会在第二天0点过5分(可能会有计时延迟)的时候重新执行各种每日的任务。

**Comment by shinji-ikari** [comment]
所以....该怎么重新触发一下让它自检确认宝箱没领完?抽奖倒是感觉挺正常的.至少过一会儿回头去看看会有增加._(:з」∠)_

**Comment by SeaLoong** [comment]
正常来说是会自动重新执行的(第二天0点过5分)。貌似你们对这个功能(每个功能完成时会记录时间，直到设定的下一次执行时间才会重新执行，本意是为了减少每次脚本加载时对各个功能检查的次数)意见有点多，我要不删了这个好了。

**Comment by shinji-ikari** [comment]
原来如此.....倒不是对这个功能有意见.反而是觉得这个功能好像有点妨碍了.辛苦大大了.o(〃'▽'〃)o
