### ISSUE TITLE
b站小电视类型的弹幕推送格式

### ISSUE THREAD

**Issue by yjqiang** [SeaLoong/Bilibili-LRHH#34]
几天之前发现，b站又启用了NOTICE_MSG这种推送办法，但是老的SYS_MSG似乎还存在，这两个好像是并存的吧。但是看你最新的代码似乎直接取代了

**Comment by SeaLoong** [comment]
对，确实是并存的。不过我觉得B站是要把这些推送给分的更细一些，目前共存可能只是在测试，将来也许会取代，因此我在代码中直接修改了。

**Comment by yjqiang** [comment]
是的应该AB测试

**Comment by yjqiang** [comment]
发现一个问题  notice_msg存在至少两种格式
一种是roomid和real_roomid均为0，此时是公告模式；以及推送小电视模式，roomid有实际意义

**Comment by yjqiang** [comment]
似乎以上两个的区分点还有msg_type但是不太确定
