### ISSUE TITLE
能不能实现每日自动投币功能？

### ISSUE THREAD

**Issue by greenzilong** [SeaLoong/Bilibili-LRHH#35]
在代码里发现

[自动每日奖励][每日投币]获取"动态-投稿视频"失败

这种字样

能不能检测每天该项任务经验，如果投币不到5个，自动投币？

**Comment by SeaLoong** [comment]
那些是我还没完成的代码（不过我手头上的已经实现了自动投币（就是你说的这种功能
现在由于其他几个功能遇到点问题，暂时没打算更新

**Comment by greenzilong** [comment]
谢谢答复

既然实现了，希望早日加入

或者新建个单独脚本

**Comment by SeaLoong** [comment]
2.3.x已经加入
