### ISSUE TITLE
舰队抽奖好像无法运行

### ISSUE THREAD

**Issue by Mintheeee** [SeaLoong/Bilibili-LRHH#36]
在脚本使用过程中无论是总督提督还是舰长都无法自动领取亲密度，请问这是什么原因呀？
期待回复，感谢~

**Comment by SeaLoong** [comment]
原因大概查明了，过段时间更新一下

**Comment by Mintheeee** [comment]
> 原因大概查明了，过段时间更新一下

十分感谢，给您捶背
