### ISSUE TITLE
关于新版本自动抽奖的时候会播放声音的问题

### ISSUE THREAD

**Issue by Xuemm233** [SeaLoong/Bilibili-LRHH#41]

**Comment by shinji-ikari** [comment]
有没有声音没注意到，不过倒是发现之前双开直播间会提示“已经有直播间运行脚本”现在的话貌似可以多挂了？而且刚才出现了，【自动抽奖】连接失败还是什么的红色字眼，不过刷新了两次又好了。

**Comment by shinji-ikari** [comment]
hmmm，可以多个直播间运行脚本之后，抛弃率这玩意儿貌似残废了。23333
看到一个直播间废掉之后，回头去看另一个直播间，另一个参加了。_(:з」∠)_

**Comment by SeaLoong** [comment]
丢弃率那玩意emmm，已经没必要了（至少我是没有封号了

**Comment by xfl03** [comment]
请提供浏览器的名称和版本

**Comment by shinji-ikari** [comment]
OH.属于特例么？还以为是可以多开之后导致的。
FIREFOX 52版本 ， greasemonkey ，关掉了B站直播的广告插件。

**Comment by xfl03** [comment]
多开是个bug，已被修复，会造成多次无意义的抽奖 @shinji-ikari 
希望 @Xuemm233 补全浏览器信息

**Comment by caw0309** [comment]
现在是会有抽奖直播间的声音，大概5秒后就没有了

**Comment by shinji-ikari** [comment]
今晚抽奖炸锅，5分钟了都还在公告，然后发现辣条不涨了。回头刷新页面。提示被封，停止运行。这锅服了_(:з」∠)~

**Comment by xfl03** [comment]
请问最新版本是否仍有此bug？
