### ISSUE TITLE
自动领瓜子失败

### ISSUE THREAD

**Issue by Saver233** [SeaLoong/Bilibili-LRHH#42]
**描述bug**
自动领瓜子失败
**重现bug**
重置后刷新关浏览器也不能恢复

**截图**
![default](https://user-images.githubusercontent.com/32214015/47785960-3d8e0680-dd45-11e8-81f9-8d4f38567b0c.png)

**使用环境:**
 - 浏览器: 如Chrome
 - 浏览器版本: 如Chromium 70.0.3538.77
 - 脚本的版本: 如2.1.0
 - 网络情况(网速): 一般
 - 其他浏览器插件/脚本: 无
 - bug出现时间: 开始初始化就有
**其他**
无

**Comment by SeaLoong** [comment]
心累

**Comment by xfl03** [comment]
![TIM截图20181031225226.png](https://i.loli.net/2018/10/31/5bd9c1c828b5e.png)
