### ISSUE TITLE
开了两天脚本后弹幕滚动栏不提示抽奖了

### ISSUE THREAD

**Issue by ldm28** [SeaLoong/Bilibili-LRHH#43]
只有直播画面上方会有抽奖提示，只能手动抽奖

**Comment by SeaLoong** [comment]
给个截图吗，破站改了丶东西

**Comment by ldm28** [comment]
![l1 9q4w4ogm lad_6fo 3](https://user-images.githubusercontent.com/20702314/47847390-092e4f00-de06-11e8-88aa-1e143df3a5f6.png)
下午3点多还是好的，后来就不能抽奖了。其他功能不知道能不能用

**Comment by SeaLoong** [comment]
破站优秀，直接取消在聊天栏显示了。我等会更新下

**Comment by Joker-hkc** [comment]
不用了，b站可能是出问题了，现在已经好了

**Comment by ldm28** [comment]
现在又能显示了，脚本也ok。之前就是b站的问题...
