### ISSUE TITLE
小黑屋

### ISSUE THREAD

**Issue by 526240218** [SeaLoong/Bilibili-LRHH#44]
今天更新后进小黑屋了。

**Comment by MrPlugy** [comment]
我也进了;-;

**Comment by Undefined-User** [comment]
~~提示下，破绽好像更新了检测系统提高了检测率，黑屋时间似乎也有加长(2w~2m？)~~

**Comment by Joker-hkc** [comment]
小黑屋什么样的？账号被封了吗？我的是还可以看直播，还可以发言，但是没法抽奖，瓜子也不行，这是什么状态

**Comment by guardianaa** [comment]
> 提示下，破绽好像更新了检测系统提高了检测率，黑屋时间似乎也有加长(2w~2m？)

2周--2月？？

**Comment by thnmko** [comment]
我也进小黑屋了，不能白嫖了，一般多久放出来呀

**Comment by zemo9108** [comment]
进了小黑屋后好像看直播都没有在线经验了呢

**Comment by thnmko** [comment]
> 进了小黑屋后好像看直播都没有在线经验了呢

有的

**Comment by zemo9108** [comment]
> > 进了小黑屋后好像看直播都没有在线经验了呢
> 
> 有的

哦，昨天的时候确实是没有，今天就有了

**Comment by heatded** [comment]
2.2.1挂舰队进了，不知道2.2.2可以挂吗

**Comment by jasonfall** [comment]
小黑屋要两周吗…之前进过两次的是不是要等更久？

**Comment by SeaLoong** [comment]
现在应该稳了，小号连续挂一天了没事

**Comment by like044041** [comment]
现在B站小黑屋越来越骚了,封了2天了,今天一看能抽奖了(手动点了一次),就把脚本打开了,结果立马封了,也不知道是我开脚本的问题,还是系统看我抽奖了就继续封了.

**Comment by zemo9108** [comment]
现在抽奖几乎都是秒抽啊，几乎都没有什么延迟的，有点慌

**Comment by SeaLoong** [comment]
延迟？取消了

**Comment by 824369906** [comment]
小黑屋多久放出来鸭

**Comment by 824369906** [comment]
一样啊，这几天小电视那么多，全部得不到

**Comment by zemo9108** [comment]
> 延迟？取消了

延迟已经取消了吗？

**Comment by like044041** [comment]
....我发现抽奖时要是提示你"出错啦，请点击重试",你可以不停的反复点,就可以参加抽奖了,但是具体按多少次速度快慢,就看运气了.....

**Comment by like044041** [comment]
舰长奖励也可以反复点,宝箱就不行了.

**Comment by huyoooooo** [comment]
已经一个星期了还没出来的我。。。封禁时间有人知道具体吗QAQ

**Comment by Cat66leo** [comment]
已经被封禁一个多星期了QAQ...破站封禁这个也不给个提醒剩余时间，也不知什么时候能解禁，有没有人知道这个封禁的一般时间哇QAQ

**Comment by fei7yang** [comment]
@Cat66leo 应该不会这么久，你是不是脚本一直开着，估计是刚出来又进去了，先全部关掉吧

**Comment by Cat66leo** [comment]
> @Cat66leo 应该不会这么久，你是不是脚本一直开着，估计是刚出来又进去了，先全部关掉吧

更新了最新的脚本后就放着了...刚刚关掉了，希望能有用QAQ谢谢你♪(･ω･)ﾉ

**Comment by 526240218** [comment]
小黑屋有出来了的没？？？

**Comment by 824369906** [comment]
> 小黑屋有出来了的没？？？

没有

**Comment by 526240218** [comment]
到底要关多久。。。

**Comment by 824369906** [comment]
> 到底要关多久。。。

上面不是好像有人说了吗，两周到两月

**Comment by 526240218** [comment]
两个月。。。简直日了狗

**Comment by MrPlugy** [comment]
刚放出来又进去了？还是一直封？

**Comment by jasonfall** [comment]
从这个帖子发出来的前1天我就封到了现在，插件什么的全关目前还没有解封，看来两个星期以上是属实了_(:з」∠)_

**Comment by 526240218** [comment]
破绽飘了，关这么久。

**Comment by silhouettecutter** [comment]
qaq我今天刚出来了。3号关到今天。9天的样子

**Comment by yxok200** [comment]
2号至今未解封

**Comment by 824369906** [comment]
一样，还在牢里( ´_ゝ｀)

**Comment by 526240218** [comment]
一样没出来

**Comment by guardianaa** [comment]
出狱了，刚刚，封了12天

**Comment by 526240218** [comment]
遥遥无期。。。

**Comment by Cat66leo** [comment]
依旧没出来，破站这是狠下心惹。。充值也没能把自己捞出来，现在慌的一批QAQ

**Comment by 526240218** [comment]
出来了，最新版还封号吗？？？

**Comment by 824369906** [comment]
是不是就我一个人还在里面(´；ω；`)

**Comment by guardianaa** [comment]
我用了一天了，还没被封

**Comment by MrPlugy** [comment]
出来了，没敢用抽奖。。。能用吗

**Comment by 824369906** [comment]
终于出来了_(:3」∠)_

**Comment by shxhmy** [comment]
我今天也出来了。。挂上插件试试

**Comment by nmbexin** [comment]
我也是昨天出狱的，大号没敢挂

**Comment by qwe088794** [comment]
13号被封，不知什么时候解封....

**Comment by thnmko** [comment]
我昨天出来了，挂了一晚上，然后现在早上挂着没事

**Comment by qwe088794** [comment]
> 13号被封，不知什么时候解封....

哦也，\(^o^)/今天17:00解封了

**Comment by shxhmy** [comment]
目前没有问题！
