### ISSUE TITLE
是自动更新吗？我还没去更新，就已经变成了新版，然后，瞬间被封了

### ISSUE THREAD

**Issue by Aduers** [SeaLoong/Bilibili-LRHH#45]
不知道怎么回事，上次更新之后今天很早就突然自动变成了新版，没了抽奖间隔什么的选项，
然后被封了，无法抽奖，一直出错，
小号现在开起来试验，看看多久被封

阅览器 搜狗

**Comment by Aduers** [comment]
旧版用了很久，有段时间更新没跟上也至少只是用不来，这次真是有点莫名，
上一个版本哪里可以找到下载？就是还保留了抽奖间隔的版本

**Comment by Aduers** [comment]
第一次被封，基本所有直播间小电视点击都会出错，
运气好打开几十个直播间，有一个能点出来领取成功的提示，但是估计没拿到辣条

这个封号到底怎么回事，小号完全没影响，大号没收到任何提示

**Comment by Aduers** [comment]
然后现在版本有一个问题，哪怕设置了十五分钟刷新页面，也还是会在直播间卡死，
页面全白，上方有半个加载符号，刷新无用，转到直播间地址没用，只能在个人直播中心的关注里打开直播间

**Comment by heatded** [comment]
自动更新是油猴设置 (我是用的油猴）的问题吧，初始是每周更新一次
历史版本就在脚本主页上，但是最新的2.2.2已经不会封号了

**Comment by heatded** [comment]
直播间卡死应该是破站问题，上午都还好，今天好像是b站活动最后一天

**Comment by SeaLoong** [comment]
用小号连续测试2天多了，没有被封。目前是基本稳定了。
按我改动代码的记忆，以及对封号检测的推测，2.1.1~2.1.3会大概率封号，2.1.1以前的版本微小概率封号
2.1.1：修复了舰队领奖不能正常工作
2.1.3：修改舰队领奖的参与方式前的最后版本

**Comment by heatded** [comment]
我是因为2.2.1的舰队抽奖被封的，2.2.2用了半天目前没有进黑屋

**Comment by Aduers** [comment]
那么估计就是了，真是坑呐，就挂了一天的过渡版本，刚好撞上我还换了个4.7新油猴，里面自己设置了更新，脸黑，应该老版本都不至于，前些天还在用2.1.X，2.2.2应该没太大问题，我也挂了几个小时，还没被封，
然后这个到底封多久？封多了会封号吗？很好奇

**Comment by Aduers** [comment]
然后我上面说的那个BUG触发之后，直播间刷新不出来，主战的网页也会概率卡死，卡在搜狗阅览器的兼容模式，无法切换，无法刷新，
多灾多难，还撞到前段时间搜狗阅览器更新，是不兼容吗

**Comment by Aduers** [comment]
不对，更新之前也会，差点记错

**Comment by jasonfall** [comment]
2.2.1会被封，2.2.2还没试过，因为还在小黑屋中…

**Comment by Aduers** [comment]
封了已经到现在了，，，这快一礼拜了，，，不会上月，永封吧，，，，

**Comment by silhouettecutter** [comment]
3号进的小黑屋，今天放出来了，9天

**Comment by qwe088794** [comment]
第一次被封会封多久？
