### ISSUE TITLE
完全小白问一下这个自动送礼物是怎么送的啊

### ISSUE THREAD

**Issue by poorsecretary** [SeaLoong/Bilibili-LRHH#46]
我在房间号里面填好了，两个类型也都是1 辣条，然后挂机了很久好像也没有送礼物的动作， 想问一下这个是每天固定几点送吗还是怎么样？
然后我是chrome

**Comment by HuangWiJay** [comment]
我也想问

**Comment by fangweiren** [comment]
同问+10086

**Comment by xfl03** [comment]
@HuangWiJay @fangweiren 
每10分钟检查一次，如果符合条件就送礼
