### ISSUE TITLE
亲眼见证了被封的瞬间。。建议大佬加个延时

### ISSUE THREAD

**Issue by FlashSaturn** [SeaLoong/Bilibili-LRHH#47]
我先说下当时的情况吧，几乎是正好看到了进小黑屋的那一瞬间
某个老板在某直播间砸了30个小电视，然后脚本在一瞬间领了这30个电视的抽奖（右侧绿色toast刷屏了）
半分钟之后，我进小黑屋了。。

大佬能不能在每次领取之间加个延时啊，300ms就够，漏抽一点真的无所谓，手速至少不要超过人类极限吧。。估计破站已经在这方面加入检测机制了

**Comment by heatded** [comment]
感觉普通抽奖已经优化的很好了，之前我一直零延时都没事，大概率是这几天舰队抽奖过于强势或者今天礼物刷屏太快导致的，刚刚边挂三个浏览器边用结果电脑当场去世
