### ISSUE TITLE
gitee有大于1M需要登录的限制..

### ISSUE THREAD

**Issue by like044041** [SeaLoong/Bilibili-LRHH#48]
更新后发现用不了,自己瞎捣鼓了一下,发现是gitee的原因.,貌似是"https://gitee.com/SeaLoong/Bilibili-LRHH/raw/master/ocrad.js" 加载不了,网页打开一看,文件大于1M，登录后可见.....

**Comment by xfl03** [comment]
已确认问题

**Comment by xfl03** [comment]
请暂时使用 `https://js-1258131272.file.myqcloud.com/OCARD.min.js` 替换 `https://gitee.com/SeaLoong/Bilibili-LRHH/raw/master/ocrad.js` 
后续会针对这一问题进行优化

**Comment by like044041** [comment]
> 请暂时使用 `https://js-1258131272.file.myqcloud.com/OCRAD.min.js` 替换 `https://gitee.com/SeaLoong/Bilibili-LRHH/raw/master/ocrad.js`
> 后续会针对这一问题进行优化

好的
我直接替换的raw.githubusercontent.com的地址

**Comment by xfl03** [comment]
还是建议用上面这个吧，压缩了js、套了腾讯云的CDN、指定了1年的缓存时间，可以非常明显的感受到加载速度的差异

**Comment by like044041** [comment]
> 还是建议用上面这个吧，压缩了js、套了腾讯云的CDN、指定了1年的缓存时间，可以非常明显的感受到加载速度的差异

好,我换新地址了

**Comment by xfl03** [comment]
已修改默认地址
