### ISSUE TITLE
更新之后舰长领奖还是无法运行

### ISSUE THREAD

**Issue by arClorisChan** [SeaLoong/Bilibili-LRHH#49]
**描述bug**
简要描述所遇到的bug

**重现bug**
说明您在进行了怎样的操作后出现了bug
1. xxx
2. xxx

**预期行为**
简要描述进行以上操作后预期的脚本行为

**截图**
如果可以，请提供有关截图

**使用环境:**
 - 浏览器: 如Chrome
 - 浏览器版本: 如Chromium 67.0.3396.99
 - 脚本的版本: 如1.0.0
 - 网络情况(网速): 好/一般/坏
 - 其他浏览器插件/脚本: 在此写上您认为可能会对本脚本产生影响的插件/脚本
 - bug出现时间: (精确到分钟)

**其他**
若您有其他想要补充的内容，请在此说明

**Comment by shinji-ikari** [comment]
[quote
注意事项/关于反馈

开启自动抽奖->礼物抽奖功能后，很容易在控制台看到许多Error，这些大多是B站的脚本错误，不用理会
要检索此脚本的控制台输出只要过滤显示带有"[BLRHH]"字样的输出即可
在脚本代码中找到有关"DEBUGMODE"的地方，将其设置为true可在控制台输出调试信息，反馈(包括bug、B站更新等)时请带上有关信息
[/quote]
无法重现环境跟问题的情况，你说了问题作者也是不知道该怎么解决的，因为找不出问题的根源。
另外，按默认内容把帖子发出来，没什么帮助。至少把默认内容看一看，填一下你知道的信息跟能提供的信息吧。

**Comment by xfl03** [comment]
请您补充详细内容
