### ISSUE TITLE
不能自动领瓜子了嘤嘤嘤

### ISSUE THREAD

**Issue by hentaishopkeeper** [SeaLoong/Bilibili-LRHH#5]
咋办啊dalao

**Comment by zodiacg** [comment]
换了新的验证码，验证码加了转动和噪点处理，短时间内解决比较难了。需要新的验证码识别的算法

**Comment by hentaishopkeeper** [comment]
我要是会码代码就好了，可惜我是文科生zzz，感觉挺难办的样子a。

**Comment by jy2lhz** [comment]
大佬快搞一套深度学习识别验证码（笑，bie dang zhen）。

**Comment by xfl03** [comment]
关于识别验证码，看到了一个似乎还不错的实现
https://github.com/zacyu/bilibili-helper/blob/a7d1403783d95061a778cc7deb653c1508383763/src/bilibili_live.js

**Comment by SeaLoong** [comment]
@xfl03 感谢提供，代码已实现，功能也可以正常用了
