### ISSUE TITLE
高效且几乎不需要后续跟进的快速查找最新实物aid的办法

### ISSUE THREAD

**Issue by yjqiang** [SeaLoong/Bilibili-LRHH#57]
aid是一个比较恶心的东西，正整数，不断递增，但是其中会有间隔（code是-400表示为空），这样的话，如何比较快速的查找到aid就是一个比较麻烦的问题。
我最终采用了类似二分的办法，从0-1000查找，经过30次左右才能查到最新数据，不清楚你是怎么做的呢？

**Comment by SeaLoong** [comment]
emmm，比较笨的办法，从我设置的最新的aid开始增加，活动存在就继续增加，直到遇到连续10次code为-400，记录最后一次存在的aid，下次从这个aid开始。

**Comment by yjqiang** [comment]
> emmm，比较笨的办法，从我设置的最新的aid开始增加，活动存在就继续增加，直到遇到连续10次code为-400，记录最后一次存在的aid，下次从这个aid开始。

感觉其实用不了10次，我是5次的。这样需要挨个查看。恶心了一点。

**Comment by SeaLoong** [comment]
反正这也影响不大，而且只是第一次需要查询很多次，之后就是十几次而已了

**Comment by yjqiang** [comment]
👌
