### ISSUE TITLE
大佬，小电视好像不能自动领了

### ISSUE THREAD

**Issue by Joisei** [SeaLoong/Bilibili-LRHH#6]

**Comment by Joisei** [comment]
过去了好几个小电视了，一点反应都没有

**Comment by wxfff** [comment]
需要先手动领几个，还有就是领了也不显示，b站已停白嫖党福利，还加密升级接口，看来脚本末路了。。。

**Comment by duanluan** [comment]
确实……我说最近怎么领的小电视都少了好多

**Comment by Joisei** [comment]
手动点小电视提示出错了，点击重试也不知道什么鬼，脚本关闭和切换浏览器都没用。。。

**Comment by wxfff** [comment]
已经被拉黑了。。。我也一样，，，

**Comment by wxfff** [comment]
手机点抽奖，显示访问被拒绝。。。。。。。彻底要凉了

**Comment by Joisei** [comment]
gg

**Comment by wxfff** [comment]
来自b站bug反馈斑竹的回复

挂领礼物的脚本或插件没有？如果有的话就是被封了，一般是次日0点解封。
--

**Comment by Joisei** [comment]
第二天能解封啊，那还行

**Comment by SeaLoong** [comment]
@xfl03 B站对抽奖做了限制，哪个房间有抽奖，就要在那个房间参加才有效(否则会被拒绝)。其原理是B站会检查Http请求头Referer是否为对应房间的，不是就拒绝抽奖的请求。
但是有特例，短号直播间如果也这样做就不能正常抽奖了，因此短号直播间是有白名单的，在短号直播间内可以参加任何直播间的抽奖。

**Comment by Joisei** [comment]
白名单的直播间有哪些啊，短号直播间是直播间房间号比较短的吗

**Comment by xfl03** [comment]
@SeaLoong 似乎自动领取小电视仍然失效
## 控制台报错
````
userscript.html?id=2b4e7cd7-33c8-471c-8333-e7b528c3b9b2:62157 
Uncaught ReferenceError: short_id is not defined
    at eval (userscript.html?id=2b4e7cd7-33c8-471c-8333-e7b528c3b9b2:62157)
````
## 定位行号
https://github.com/SeaLoong/Bilibili-LRHH/blob/master/Bilibili%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.js#L306

**Comment by xfl03** [comment]
@SeaLoong 您说的没错，不过我手动加入`var`以后只是不报错了，也没能够正常工作

**Comment by SeaLoong** [comment]
@xfl03 已更新，修复了不能正常抽奖的问题
