### ISSUE TITLE
直播间页面找不到右下角的设置按钮

### ISSUE THREAD

**Issue by Lancezzzzzz** [SeaLoong/Bilibili-LRHH#63]
**描述bug**
[直播间页面找不到右下角的设置按钮，没有挂机助手设置，这个按钮

**重现bug**
说明您在进行了怎样的操作后出现了bug
1. 系统重装

**预期行为**
简要描述进行以上操作后预期的脚本行为

**截图**
如果可以，请提供有关截图

**使用环境:**
 - 浏览器: 如Chrome
 - 浏览器版本: Google Chrome 已是最新版本
版本 73.0.3683.86（正式版本） （64 位）

 - 脚本的版本: 如2.3.12
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本: 在此写上您认为可能会对本脚本产生影响的插件/脚本
 - bug出现时间: (精确到分钟)2019/3/22/16/07

**其他**
若您有其他想要补充的内容，请在此说明

**Comment by Lancezzzzzz** [comment]
<img width="1920" alt="捕获" src="https://user-images.githubusercontent.com/48841637/54850126-a35f3880-4cbc-11e9-8e57-2beed30129fb.PNG">
图为证

**Comment by SeaLoong** [comment]
按下F12看看控制台提示什么

**Comment by Lancezzzzzz** [comment]
刚刚你更新了吧，现在好了，麻烦了

**Comment by SeaLoong** [comment]
(黑人问号.jpg)我只是更新了下API部分
