### ISSUE TITLE
移动端看5分钟直播任务无法完成

### ISSUE THREAD

**Issue by like044041** [SeaLoong/Bilibili-LRHH#65]
**描述bug**
移动端看5分钟直播任务无法完成
**重现bug**
说明您在进行了怎样的操作后出现了bug
昨天可以完成,今天就不行了

[**截图**]
![2019-4-2 15-6-55](https://user-images.githubusercontent.com/33434924/55383665-594b4200-555b-11e9-9b81-16d7e93d59d7.png)

**使用环境:**
 - 浏览器: Chrome
 - 浏览器版本: Chromium 72.0.3626.121
 - 脚本的版本: 最新2.3.14
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本: 无
 - bug出现时间: 今天

**Comment by SeaLoong** [comment]
我这没法复现

**Comment by like044041** [comment]
> 我这没法复现

我再试试吧

**Comment by like044041** [comment]
哎我去,挂了一天都不行,刚才又突然完成任务了,莫名其妙,不好意思了,我关了
