### ISSUE TITLE
B站可能更新规则了，我的账号已经小黑屋了

### ISSUE THREAD

**Issue by mylongdays** [SeaLoong/Bilibili-LRHH#66]
建议给用户们推行个更新提醒下，是否继续使用由用户自己决定。

**Comment by guardianaa** [comment]
我没事儿啊

**Comment by mylongdays** [comment]
> 我没事儿啊

我已经九天不能抽奖了，瓜子可能更早就不能领了但我没注意。

**Comment by ldm28** [comment]
除了每日任务的双端观看失效了，其他都正常

**Comment by mylongdays** [comment]
> 除了每日任务的双端观看失效了，其他都正常

我反而是双端有效

**Comment by like044041** [comment]
我也是双端任务不行,前两天还好的,这两天不行了,移动端无法完成,其他都好

**Comment by MubaiDust** [comment]
啊我才挂两天就小黑屋了...晚上才发现

**Comment by V-Koo** [comment]
请问这个脚本是必须保持在直播间内才能运行吗，是不是退出直播间后就自动停止运行了？

**Comment by mylongdays** [comment]
> 请问这个脚本是必须保持在直播间内才能运行吗，是不是退出直播间后就自动停止运行了？

需要一直开着直播间，关了就不行了，这个脚本的原理是接收评论里的抽奖弹幕，关了直播间就收不到弹幕了

**Comment by yogurt414** [comment]
最近总是要我验证身份，已经被怀疑了

**Comment by like044041** [comment]
> 除了每日任务的双端观看失效了，其他都正常

我试了试,设置一下新密码,双端任务就能正常完成了,要是还不能完成,就把所有B站网页都关了,再修改密码.

**Comment by SeaLoong** [comment]
小黑屋的问题见多了，该用的还是用，没必要提示。
