### ISSUE TITLE
领瓜子启动失败

### ISSUE THREAD

**Issue by emodeshengge** [SeaLoong/Bilibili-LRHH#69]
2019.5.6最新的谷歌浏览器，初始化脚本时领瓜子程序启动失败

**Comment by xfl03** [comment]
请问[常见问题](https://github.com/SeaLoong/Bilibili-LRHH/blob/master/README.md#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)第一条是否已尝试？

**Comment by emodeshengge** [comment]
我只找到了这一段，然后没有找到bilibiliapl的那一段代码，还有一个说将两个网址内的代码替换，我打开网页读取代码没问题，但是复制的时候浏览器直接自闭了，所以没有能够替换成功。
如下图：




------------------ 原始邮件 ------------------
发件人: "Alexander Xia"<notifications@github.com>;
发送时间: 2019年5月6日(星期一) 晚上6:39
收件人: "SeaLoong/Bilibili-LRHH"<Bilibili-LRHH@noreply.github.com>;
抄送: "那一抹曙光"<1647332921@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [SeaLoong/Bilibili-LRHH] 领瓜子启动失败 (#69)




请问常见问题第一条是否已尝试？

**Comment by xfl03** [comment]
```
// @require      https://js-1258131272.file.myqcloud.com/BilibiliAPI.js
// @require      https://js-1258131272.file.myqcloud.com/OCRAD.min.js
```
请先尝试换成这个，以及图片未能成功上传。

**Comment by emodeshengge** [comment]
![QQ图片20190507082541](https://user-images.githubusercontent.com/46430678/57263054-c8a7da80-70a1-11e9-9740-680f5e6c2070.jpg)
![QQ图片20190507082548](https://user-images.githubusercontent.com/46430678/57263055-c8a7da80-70a1-11e9-8fa2-c3dd82c57e15.png)
![QQ图片20190507082554](https://user-images.githubusercontent.com/46430678/57263056-c8a7da80-70a1-11e9-82bc-4d8629885fa5.png)
![QQ图片20190507082559](https://user-images.githubusercontent.com/46430678/57263057-c9407100-70a1-11e9-901b-33c3cedb1be0.png)
![QQ图片20190507082604](https://user-images.githubusercontent.com/46430678/57263058-c9407100-70a1-11e9-96ba-4d4d1b739f50.png)
![QQ图片20190507082608](https://user-images.githubusercontent.com/46430678/57263059-c9d90780-70a1-11e9-95eb-d136054e4cb5.png)
全部都在里面了，今天尝试以后依旧失败，很遗憾

**Comment by xfl03** [comment]
你这根本就没有修改啊，修改的结果如下图所示：
![2019-05-07.png](https://i.loli.net/2019/05/07/5cd0fd1ac5475.png)

**Comment by emodeshengge** [comment]
原来是那里！谢谢，有截图看着就清晰多了，已经修改完成！
程序已经能够正常使用！
