### ISSUE TITLE
在某些直播间（如5086）脚本无法运行

### ISSUE THREAD

**Issue by cloudreflection** [SeaLoong/Bilibili-LRHH#74]
脚本启用正常，在其他直播间运行正常的情况下，在直播间5086（[https://live.bilibili.com/5086](url)）中无法运行，即油猴显示启用，但网页上什么也没有显示。

**Comment by SeaLoong** [comment]
在一些特殊的直播间确实无法运行，因为是按照一般的直播间页面写的。
