### ISSUE TITLE
已拦截跨源请求：同源策略禁止

### ISSUE THREAD

**Issue by rufengsuixing** [SeaLoong/Bilibili-LRHH#75]
**描述bug**
[BLRHH]SubScript:[19:56:22:46] Lottery.Gift.run: API.Lottery.Gift.check: 
已拦截跨源请求：同源策略禁止读取位于 https://api.live.bilibili.com/gift/v3/smalltv/join 的远程资源。（原因：CORS 头缺少 'Access-Control-Allow-Origin'）。

[BLRHH][下午7:56:22][自动抽奖][礼物抽奖]参加抽奖(roomid=266481,raffleId=365225)失败，请检查网络

**重现bug**
说明您在进行了怎样的操作后出现了bug
1. 刷新

**预期行为**
成功

**截图**
![图片](https://user-images.githubusercontent.com/22387141/62046824-7ce97500-b23b-11e9-8c57-79f80c33be49.png)

**使用环境:**
火狐 windows10 tempermonkey

**其他**
若您有其他想要补充的内容，请在此说明

**Comment by SeaLoong** [comment]
B站改了接口，已更新
