### ISSUE TITLE
2.4.1更新后一直被小黑屋

### ISSUE THREAD

**Issue by sd2333** [SeaLoong/Bilibili-LRHH#76]
**描述bug**
2.4.1更新后一直被小黑屋

**使用环境:**
 - 浏览器: Chrome
 - 浏览器版本: 76.0.3809.87（正式版本） （64 位）
 - 脚本的版本: 2.4.1
 - 网络情况(网速): 好
 - bug出现时间: 进入直播间立马封

**Comment by jokin1999** [comment]
暂时没有遇到，一切正常

**Comment by sd2333** [comment]
更新后一直这样，一进就封



------------------ 原始邮件 ------------------
发件人: "Jokin"<notifications@github.com>; 
发送时间: 2019年8月4日(星期天) 晚上9:15
收件人: "SeaLoong/Bilibili-LRHH"<Bilibili-LRHH@noreply.github.com>; 
抄送: "蛋蛋"<616726835@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [SeaLoong/Bilibili-LRHH] 2.4.1更新后一直被小黑屋 (#76)




暂时没有遇到，一切正常

**Comment by jokin1999** [comment]
我刚刚试过，表示一切正常，可能个别情况？或者是使用过别的什么助手？

**Comment by sputniksea** [comment]
自動抽獎訪問被拒絕QAQ

**Comment by darth-zhang** [comment]
月初刚充过钱的，结果还是被封了，别人有这种情况吗？

**Comment by zhoor120** [comment]
昨天也被封了 一天 qaq

**Comment by SeaLoong** [comment]
被封是正常现象，另外不是进入直播间就封，只是脚本告诉你被封了

**Comment by skycity233** [comment]
我昨天也被封了，估计会被封一个月，几个月前已经封过一个月了。
