### ISSUE TITLE
建议增加分区 娱乐-虚拟主播

### ISSUE THREAD

**Issue by gimfia** [SeaLoong/Bilibili-LRHH#79]
无BUG，建议增加监听分区 娱乐-虚拟主播

**Comment by SeaLoong** [comment]
这不是也算在娱乐区的吗？

**Comment by gimfia** [comment]
> 这不是也算在娱乐区的吗？

可是每次都没有领到礼物...试过好几次了，房间都没有领到

**Comment by gimfia** [comment]
> 这不是也算在娱乐区的吗？

难道是我监听倍数没开够吗？原来是三倍，我现在开五倍试试
