### ISSUE TITLE
为什么1.8.1版本的自动领瓜子还是没用啊

### ISSUE THREAD

**Issue by hentaishopkeeper** [SeaLoong/Bilibili-LRHH#8]
进入指定页面后过一段时间脚本才开始启动，自动领瓜子还是无用这样正常ma？

**Comment by hentaishopkeeper** [comment]
而且还不如1.7.Xd的版本...那个玩意还能自动签到，这个不知道为什么没了。我自己尝试了一下我没有被封

**Comment by xfl03** [comment]
## 控制台报错
````
userscript.html?id=2b4e7cd7-33c8-471c-8333-e7b528c3b9b2:62157 
Uncaught ReferenceError: short_id is not defined
    at eval (userscript.html?id=2b4e7cd7-33c8-471c-8333-e7b528c3b9b2:62157)
````
## 定位行号
https://github.com/SeaLoong/Bilibili-LRHH/blob/master/Bilibili%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.js#L306

**Comment by hentaishopkeeper** [comment]
是我操作姿势有问题吗？领瓜子和自动抽奖功能确实是没有工作啊...

**Comment by xfl03** [comment]
自动抽奖功能的确仍然存在问题，已在隔壁反馈
不过领取瓜子这里包括验证码识别都是正常工作了
或许您可以看下控制台有无报错之类的？

**Comment by xfl03** [comment]
不要慌，问题不打，主要原因是由于网络问题无法加载OCRAD
`https://greasyfork.org/scripts/44866-ocrad/code/OCRAD.js`
请尝试一下上面那个链接能够正常访问，如果可以的刷新页面即可

**Comment by hentaishopkeeper** [comment]
能访问呢 但是我已经刷新好几次了没有有用啊QAQ

**Comment by hentaishopkeeper** [comment]
我把OCRAD.js放入我的tamper刷新一下之后也没用呢

**Comment by hentaishopkeeper** [comment]
报错内容是这个啊... 

Uncaught ReferenceError: OCRAD is not defined

**Comment by xfl03** [comment]
主要问题是
`Couldn't load @require from URL https://greasyfork.org/scripts/44866-ocrad/code/OCRAD.js`
也是因为这个js无法加载导致了
`OCRAD is not defined`

**Comment by hentaishopkeeper** [comment]
这个网站我是能正常加载的啊...我还把这个js扔到tampermonkey了

**Comment by xfl03** [comment]
> js扔到tampermonkey  
  
这是一个无意义行为，依赖会从URL而不是本地加载
请确认一下Network里到底为什么没能加载成功

**Comment by hentaishopkeeper** [comment]
我全局ss了一下还是有这个错误，重启电脑也没用...

**Comment by SeaLoong** [comment]
@hentaishopkeeper 确保这两个文件都有
![qq 20180430225208](https://user-images.githubusercontent.com/9292758/39433744-36e4eeb4-4cc9-11e8-8ba7-c3870aa0f9a7.png)

**Comment by hentaishopkeeper** [comment]
@SeaLoong 
![default](https://user-images.githubusercontent.com/38519018/39433893-9eb256f8-4cc9-11e8-93de-702e1f7ce549.PNG)

我是这样的啊...

**Comment by hentaishopkeeper** [comment]
@xfl03 
![2](https://user-images.githubusercontent.com/38519018/39433919-b00a46a4-4cc9-11e8-83d2-ac2e63d19bd7.PNG)
没有发现奇怪的东西呢...

**Comment by SeaLoong** [comment]
@hentaishopkeeper 你把库丢这里是没用的= =

**Comment by hentaishopkeeper** [comment]
![Uploading 捕获45.PNG…]()
![21](https://user-images.githubusercontent.com/38519018/39434179-69b60480-4cca-11e8-868d-9fa6663f44ee.PNG)
好吧发现了盲点... 0字节的...怎么办呢

**Comment by hentaishopkeeper** [comment]
![333](https://user-images.githubusercontent.com/38519018/39434333-e70ab4b2-4cca-11e8-8971-e123f8e2cb0a.PNG)

天哪莫名其妙...突然就好了....我一脸懵逼
问题解决了，谢谢开发者的耐心回答！赞美您！

什么鬼啊233
