### ISSUE TITLE
最近B站好像更新了上舰领奖，小电视抽奖机制，我的弹幕助手不会自动去褥辣条了

### ISSUE THREAD

**Issue by flow4headphone** [SeaLoong/Bilibili-LRHH#80]
**描述bug**
最近B站好像更新了上舰领奖，小电视抽奖机制，我的弹幕助手不会自动去褥辣条了，重新设置之后直播间页面也会不停的刷新（刷新频率设置了0，应该是关闭的）

**重现bug**
说明您在进行了怎样的操作后出现了bug
1. 如上
2. 如上

**预期行为**
应该会自动褥辣条，并且不会自动刷新页面

**截图**
如果可以，请提供有关截图

**使用环境:**
 - 浏览器: Chrome
 - 浏览器版本: 76.0.3809.100（正式版本） 
 - 脚本的版本: 2.4.3
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本: 在此写上您认为可能会对本脚本产生影响的插件/脚本
 - bug出现时间: 每次打开B站直播间网页

**其他**
若您有其他想要补充的内容，请在此说明

**Comment by YanF233** [comment]
的确平常我一个中午能褥好几百根现在只有几十根。。。

**Comment by kaho716** [comment]
对。。之前还不可以拿好多。。，现在一个都拿不到

**Comment by SeaLoong** [comment]
监听倍数别开太高，现在是做了对每个监听的直播间开个子页面来处理舰队相关，所以刚进的时候会开很多页面，而我又做了超过50个子页面就会自动刷新防止崩溃。

**Comment by penuser** [comment]
> 监听倍数别开太高，现在是做了对每个监听的直播间开个子页面来处理舰队相关，所以刚进的时候会开很多页面，而我又做了超过50个子页面就会自动刷新防止崩溃。

请问自动抽奖Console报“参数错误”也在此范围内吗？
偶尔还会报“抽奖尚未开始”的错误。

**Comment by SeaLoong** [comment]
> > 监听倍数别开太高，现在是做了对每个监听的直播间开个子页面来处理舰队相关，所以刚进的时候会开很多页面，而我又做了超过50个子页面就会自动刷新防止崩溃。
> 
> 请问自动抽奖Console报“参数错误”也在此范围内吗？
> 偶尔还会报“抽奖尚未开始”的错误。

估计是改了，不让提前参加抽奖了。不过按理说我新版做了延时处理，问题应该不会很大。有空我再看看。

**Comment by darth-zhang** [comment]
现在最大的问题是一次送多个礼物时候只会自动抽一个，无火佬的十连百连小电视都得手动领剩下的，以前是可以抽这种一次送多个礼物的，是不是raffleID过滤那里出问题了？
