### ISSUE TITLE
disscussion

### ISSUE THREAD

**Issue by jasonfall** [SeaLoong/Bilibili-LRHH#83]
前天自动抽奖中了一个尼禄手办(当天没发现，被一堆私信轰炸了才看到…)，虽然说抽奖本来就是0成本的，但感觉用脚本抽奖中了还是像偷来的一样，所以想不到发哪里只好发这里来了。最后还是感谢大大做的脚本，真的挺开心的。

**Comment by g2384** [comment]
吓得我赶紧看了看我的私信……果然什么也没有，安心了😌
