### ISSUE TITLE
助手不能用了

### ISSUE THREAD

**Issue by Kirachiu** [SeaLoong/Bilibili-LRHH#84]
**描述bug**
一直显示与服务器连接断开，尝试重连。
这是被关小黑屋了吗？

**Comment by guyunguyun** [comment]
我也是，已经两三天了，一直断开重连。

**Comment by OOYUKIOO** [comment]
我也是，显示不同分区的弹幕服务器断开连接。但是自动抽奖好像还在工作，背包里还会出现辣条。

**Comment by DeSireFire** [comment]
我也碰到了

**Comment by DeSireFire** [comment]
![image](https://user-images.githubusercontent.com/18726905/64501646-c88c4580-d2f4-11e9-8cb1-2d338b1b62ee.png)
感觉是一种新型黑屋？还是说领取机制变了

**Comment by Kirachiu** [comment]
78.0.3902.4? 官方才77呀
