### ISSUE TITLE
请教一个问题，B站是否可以实现 自动发送动态，并非转发其他人动态

### ISSUE THREAD

**Issue by BlueskyClouds** [SeaLoong/Bilibili-LRHH#86]
最新想写一个走某网站自动获取随后自动发送B站动态，但是发现tok正确，也正常登陆了就是无法发送，返回400，我感觉是我Cookie少了很多东西。

**Comment by SeaLoong** [comment]
这个抓下接口，找对应参数填一下就行。
另外问问题/技术交流什么的可以加Q群，群号在最下面几个issue里有发过。
