### ISSUE TITLE
总是跳出部分分区的弹幕服务器断开链接

### ISSUE THREAD

**Issue by twologbook** [SeaLoong/Bilibili-LRHH#89]
**描述bug**
成功进入弹幕服务器后总是跳出部分分区的弹幕服务器断开链接，但能参加部分抽奖

**重现bug**
正常连接弹幕服务器后总是跳出部分分区弹幕服务器断开

**预期行为**

**截图**

![1](https://user-images.githubusercontent.com/20291066/65600699-39a94980-dfd3-11e9-8e81-3e653ad30de5.JPG)
![2](https://user-images.githubusercontent.com/20291066/65600713-42018480-dfd3-11e9-80c6-7d5193d4c1ee.JPG)
![3](https://user-images.githubusercontent.com/20291066/65600714-42018480-dfd3-11e9-953c-147d7cbcce25.JPG)
![捕获](https://user-images.githubusercontent.com/20291066/65600724-46c63880-dfd3-11e9-914e-068c72176e1b.JPG)
![捕获1](https://user-images.githubusercontent.com/20291066/65600726-46c63880-dfd3-11e9-9d06-766819525bd6.JPG)

**使用环境:**
 - 浏览器: Chrome
 - 浏览器版本: 版本 76.0.3809.132（正式版本） （64 位）
 - 脚本的版本: 2.4.3
 - 网络情况(网速): 200M联通光纤
 - 其他浏览器插件/脚本: 无
 - bug出现时间: 成功连接后五六秒开始不断跳出

**其他**

**Comment by ykozxy** [comment]
+1，同样问题

**Comment by NeroArc** [comment]
+1 同样出现上述问题

**Comment by Matayoru233** [comment]
+1,也是同样出现上述问题

**Comment by JimMoen** [comment]
同样出现上述问题，推测可能为B站直播对于直播间的链接检测方式有所更改。

**Comment by Fubuki521** [comment]
+1，相同问题

**Comment by sca-rab** [comment]
+1 同样出现上述问题

**Comment by kenyeson** [comment]
+1同样出现上述问题

**Comment by mindechen** [comment]
+1同样出现上述问题

**Comment by SeaLoong** [comment]
在修了在修了

**Comment by twologbook** [comment]
今天更新后已经没问题了，十分感谢~
