### ISSUE TITLE
1.8.2版本进直播间没自动启用

### ISSUE THREAD

**Issue by lokayimasi** [SeaLoong/Bilibili-LRHH#9]
看了下控制台，提示这个，请问如何解决，谢谢
![111](https://user-images.githubusercontent.com/32692275/39433176-cc841da2-4cc7-11e8-9108-04bebb3c13f8.PNG)

**Comment by lemako** [comment]
我本来也这样 ctrl+F5了几次就好了……

**Comment by SeaLoong** [comment]
这个应该是插件的问题，或许刷新几次就行了？

**Comment by lokayimasi** [comment]
emmm,按你们说的刷新和强制刷新也没有解决

**Comment by lokayimasi** [comment]
然后把tampermonkey换成violentmonkey问题解决了
