### ISSUE TITLE
抽奖的时候一直显示：与弹幕服务器连接断开，尝试重连

### ISSUE THREAD

**Issue by XiaoYao0202** [SeaLoong/Bilibili-LRHH#90]
**描述bug**
简要描述所遇到的bug

**重现bug**
说明您在进行了怎样的操作后出现了bug
1. 勾上自动抽奖

**预期行为**
简要描述进行以上操作后预期的脚本行为

**截图**
如果可以，请提供有关截图
![image](https://user-images.githubusercontent.com/36102850/65845691-c6565d80-e36d-11e9-8f3b-ed898e4a1204.png)

**使用环境:**
 - 浏览器: 如Chrome
 - 浏览器版本: 如Chromium 67.0.3396.99
 - 脚本的版本: 如1.0.0
 - 网络情况(网速): 好/一般/坏
 - 其他浏览器插件/脚本: 在此写上您认为可能会对本脚本产生影响的插件/脚本
 - bug出现时间: (精确到分钟)

**其他**
若您有其他想要补充的内容，请在此说明

**Comment by RT216** [comment]
已经更新到了2.4.4最新版本，但近期再次出现同样问题（抽奖的时候一直显示：与弹幕服务器连接断开，尝试重连）

**Comment by kenyeson** [comment]
同上
浏览器：Chrome
浏览器版本：77.0.3865.90（正式版本） （64 位）
脚本的版本：2.4.4

**Comment by ldm28** [comment]
火狐2.4.4还没有这个问题,但我发现上任总督不会领取亲密度
