### ISSUE TITLE
现在启动这个会说您的账号被关小黑屋无法自动领瓜子

### ISSUE THREAD

**Issue by Matayoru233** [SeaLoong/Bilibili-LRHH#91]
我的账号实际上没有关小黑屋，但是这个运行就会说被关小黑屋了，关闭这个就可以手动领了，是不是B站更新了检测规则呢

**Comment by xfl03** [comment]
请给出控制台显示的内容

**Comment by Matayoru233** [comment]
大概是
![image](https://user-images.githubusercontent.com/55798244/66264527-990c2280-e839-11e9-8fd4-a54f7cd4a48b.png)这个，有可能真的被封禁了？我去主站小黑屋显示状态正常，是主站和直播不同吗？上面说关掉就可以领了应该是错的，我关了现在好像也说访问被拒绝，我再试试吧，可能使用这个被检测到了吗
