### ISSUE TITLE
无法自动领瓜子

### ISSUE THREAD

**Issue by ishkong** [SeaLoong/Bilibili-LRHH#93]
**描述bug**
最新版本无法自动领取瓜子，上一个版本在领瓜子的时候会导致面页全部卡死一小段时间

**重现bug**
一直存在，提示 ocrad初始化失败

**使用环境:**
 - 浏览器: Chrome
 - 浏览器版本: 77.0.3865.120 (正式版本) （64 位） (cohort: 77_120_Win)
 - 脚本的版本: 2.4.5
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本: 已按照要求关闭了广告拦截插件

**其他**
最新版本无法自动领取瓜子，上一个版本可以领瓜子但是领的时候会导致面页全部卡死一小段时间

**Comment by cos-fish** [comment]
老哥你换源了吗？
