### ISSUE TITLE
显示连接失败或者舰队领奖已经领取过

### ISSUE THREAD

**Issue by Fubuki521** [SeaLoong/Bilibili-LRHH#97]
**描述bug**
简要描述所遇到的bug
显示连接失败或者舰队领奖显示已经领取过，但是辣条好像还是能正常领

**重现bug**
说明您在进行了怎样的操作后出现了bug
打开页面后十几秒就显示了

**预期行为**
简要描述进行以上操作后预期的脚本行为

**截图**
如果可以，请提供有关截图
![批注 2019-12-01 230826](https://user-images.githubusercontent.com/55498866/69915950-dd115180-148f-11ea-8ecf-d3d0de50944f.png)
![批注 2019-12-01 230835](https://user-images.githubusercontent.com/55498866/69915951-dd115180-148f-11ea-9fdc-1c1f0c3a1f01.png)
![批注 2019-12-01 230916](https://user-images.githubusercontent.com/55498866/69915952-dda9e800-148f-11ea-92c4-98c0797b9afa.png)

**使用环境:**
 - 浏览器: Chrome
 - 浏览器版本:  80.0.3970.5（正式版本）dev
 - 脚本的版本: 最新的2.4.9
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本: 应该没有
 - bug出现时间: (精确到分钟)大概十几秒

**其他**
若您有其他想要补充的内容，请在此说明

**Comment by Fubuki521** [comment]
现在连接断开的问题没有了，但是舰队领奖的问题依然还在 
![批注 2019-12-07 213729](https://user-images.githubusercontent.com/55498866/70375607-7c27c480-193a-11ea-97b6-b8df701cd943.png)
![批注 2019-12-07 213832](https://user-images.githubusercontent.com/55498866/70375608-7c27c480-193a-11ea-84a1-268e7b51e81b.png)

**Comment by SeaLoong** [comment]
这个是因为B站把领取过和未领取过的标记改成一样了，导致判断为领取过。目前不影响使用。
